let
    Source = Excel.Workbook(File.Contents("C:\Users\Owner\Desktop\Data science continuation training\datasets for Great Powr Competition\Global military power comparison no source\GLOBAL_FIREPOWER_2021.xlsx"), null, true),
    GLOBAL_FIREPOWER_2021_Sheet = Source{[Item="GLOBAL_FIREPOWER_2021",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(GLOBAL_FIREPOWER_2021_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country", type text}, {"Country_Code", type text}, {"PowerIndex", type any}, {"TotalPopulation", Int64.Type}, {"Available_Military_Manpower", Int64.Type}, {"Fit_for_service", Int64.Type}, {"Reaching_Military_Age_Anually", Int64.Type}, {"Active_Service", Int64.Type}, {"Active_Reserves", Int64.Type}, {"Paramilitary_Force", Int64.Type}, {"Aircraft_Fleet_Strength", Int64.Type}, {"Fighters_Interceptors_Strength", Int64.Type}, {"Attack_Aircraft_Strength", Int64.Type}, {"Fixed-wing_Strength", Int64.Type}, {"Trainer_Aircraft_Strength", Int64.Type}, {"Special-mission_Aircraft_Strength", Int64.Type}, {"Tanker_Fleet_Aircraft_Strength", Int64.Type}, {"Total_Helicopter__Fleet_Strength", Int64.Type}, {"Attack_Helicopter_Fleet_Strength", Int64.Type}, {"Total_Combat_Tank_Strength", Int64.Type}, {"Armored_Vehicle_Strength", Int64.Type}, {"Self-Propelled_Artillery_Strength", Int64.Type}, {"Rocket_Projector_Strength", Int64.Type}, {"Naval_Fleet_Strength", Int64.Type}, {"Aircraft_Carrier_Fleet_Strength", Int64.Type}, {"Helicopter_Carriers_Fleet_Strength", Int64.Type}, {"Submarine_Fleet_Strength", Int64.Type}, {"Destroyers_Fleet_Strength", Int64.Type}, {"Frigates_Fleet_Strength", Int64.Type}, {"Corvettes_Fleet_Strength", Int64.Type}, {"Offshore_Patrol_Vessel_Fleet_Strength", Int64.Type}, {"Mine_Warfare_Fleet_Strength", Int64.Type}, {"Annual_Defense_Spending_Budget", Int64.Type}, {"External_Debt", Int64.Type}, {"Purchasing_Power_Parity", Int64.Type}, {"Reserves_Of_Foreign_Exchange_And_Gold", Int64.Type}, {"Serviceable_Airports", Int64.Type}, {"Trade_Terminals_And_Ports", Int64.Type}, {"Merchant_Marine_Fleet_Strength", Int64.Type}, {"Railway_Cowerage_km", Int64.Type}, {"Roadway_Coverage_km", Int64.Type}, {"Oil_Production_bbl", Int64.Type}, {"Oil_Consumption_bbl", Int64.Type}, {"Proven_Oil_reserves_bbl", Int64.Type}, {"Square_Land_Arena_km", Int64.Type}, {"Coastline_Coverage_km", Int64.Type}, {"Border_Coverage_km", Int64.Type}, {"Waterway_Coverage_km", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Country_Code", "Country Code"}, {"Annual_Defense_Spending_Budget", "Annual Defense Spending"}}),
    #"Appended Mil spendng from 60 to Global Fire which included 2021 spending" = Table.Combine({#"Renamed Columns", #"COPY military spending by country from 1960 thru 2019\"}),
    #"Replaced null with 2020" = Table.ReplaceValue(#"Appended Mil spendng from 60 to Global Fire which included 2021 spending",null,"2020",Replacer.ReplaceValue,{"Year"}),
    #"Appended income by country to Global firepower" = Table.Combine({#"Replaced null with 2020", #"use income group column from this Metadata_Country"}),
    #"Removed Columns" = Table.RemoveColumns(#"Appended income by country to Global firepower",{"SpecialNotes"}),
    #"Removed Blank Rows" = Table.SelectRows(#"Removed Columns", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Filtered Rows" = Table.SelectRows(#"Removed Blank Rows", each ([Country] <> null and [Country] <> "" and [Country] <> "Arab World" and [Country] <> "Ivory Coast")),
    #"Removed Purchasing Power Parity" = Table.RemoveColumns(#"Filtered Rows",{"Purchasing_Power_Parity"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Purchasing Power Parity",{"Country", "Country Code", "PowerIndex", "Annual Defense Spending", "Year", "TotalPopulation", "Available_Military_Manpower", "Fit_for_service", "Reaching_Military_Age_Anually", "Active_Service", "Active_Reserves", "Paramilitary_Force", "Aircraft_Fleet_Strength", "Fighters_Interceptors_Strength", "Attack_Aircraft_Strength", "Fixed-wing_Strength", "Trainer_Aircraft_Strength", "Special-mission_Aircraft_Strength", "Tanker_Fleet_Aircraft_Strength", "Total_Helicopter__Fleet_Strength", "Attack_Helicopter_Fleet_Strength", "Total_Combat_Tank_Strength", "Armored_Vehicle_Strength", "Self-Propelled_Artillery_Strength", "Rocket_Projector_Strength", "Naval_Fleet_Strength", "Aircraft_Carrier_Fleet_Strength", "Helicopter_Carriers_Fleet_Strength", "Submarine_Fleet_Strength", "Destroyers_Fleet_Strength", "Frigates_Fleet_Strength", "Corvettes_Fleet_Strength", "Offshore_Patrol_Vessel_Fleet_Strength", "Mine_Warfare_Fleet_Strength", "External_Debt", "Reserves_Of_Foreign_Exchange_And_Gold", "Serviceable_Airports", "Trade_Terminals_And_Ports", "Merchant_Marine_Fleet_Strength", "Railway_Cowerage_km", "Roadway_Coverage_km", "Oil_Production_bbl", "Oil_Consumption_bbl", "Proven_Oil_reserves_bbl", "Square_Land_Arena_km", "Coastline_Coverage_km", "Border_Coverage_km", "Waterway_Coverage_km", "Region", "IncomeGroup"}),
    #"Merged income group" = Table.NestedJoin(#"Reordered Columns", {"Country Code"}, #"use income group column from this Metadata_Country", {"Country Code"}, "use income group column from this Metadata_Country", JoinKind.LeftOuter),
    #"Expanded use income group column from this Metadata_Country" = Table.ExpandTableColumn(#"Merged income group", "use income group column from this Metadata_Country", {"IncomeGroup"}, {"use income group column from this Metadata_Country.IncomeGroup"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Expanded use income group column from this Metadata_Country",{"IncomeGroup"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"use income group column from this Metadata_Country.IncomeGroup", "Income Group"}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns1",{"Country", "Income Group", "Country Code", "PowerIndex", "Annual Defense Spending", "Year", "TotalPopulation", "Available_Military_Manpower", "Fit_for_service", "Reaching_Military_Age_Anually", "Active_Service", "Active_Reserves", "Paramilitary_Force", "Aircraft_Fleet_Strength", "Fighters_Interceptors_Strength", "Attack_Aircraft_Strength", "Fixed-wing_Strength", "Trainer_Aircraft_Strength", "Special-mission_Aircraft_Strength", "Tanker_Fleet_Aircraft_Strength", "Total_Helicopter__Fleet_Strength", "Attack_Helicopter_Fleet_Strength", "Total_Combat_Tank_Strength", "Armored_Vehicle_Strength", "Self-Propelled_Artillery_Strength", "Rocket_Projector_Strength", "Naval_Fleet_Strength", "Aircraft_Carrier_Fleet_Strength", "Helicopter_Carriers_Fleet_Strength", "Submarine_Fleet_Strength", "Destroyers_Fleet_Strength", "Frigates_Fleet_Strength", "Corvettes_Fleet_Strength", "Offshore_Patrol_Vessel_Fleet_Strength", "Mine_Warfare_Fleet_Strength", "External_Debt", "Reserves_Of_Foreign_Exchange_And_Gold", "Serviceable_Airports", "Trade_Terminals_And_Ports", "Merchant_Marine_Fleet_Strength", "Railway_Cowerage_km", "Roadway_Coverage_km", "Oil_Production_bbl", "Oil_Consumption_bbl", "Proven_Oil_reserves_bbl", "Square_Land_Arena_km", "Coastline_Coverage_km", "Border_Coverage_km", "Waterway_Coverage_km", "Region"}),
    #"Filtered Rows1" = Table.SelectRows(#"Reordered Columns1", each ([Country] <> "Africa Eastern and Southern" and [Country] <> "Africa Western and Central")),
    #"replaced null with data not avail" = Table.ReplaceValue(#"Filtered Rows1",null,"data not avail",Replacer.ReplaceValue,{"Income Group"})
in
    #"replaced null with data not avail"
